### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by dtracers** [jjbott/RocketLeagueReplayParser#35]
Hey we in carball (https://github.com/SaltieRL/carball) are trying to switch to a new parser from rattletrap for performance reasons. 

And I was wondering if we could chat?
(Couldn't find a way to contact you)

**Comment by tfausak** [comment]
I was going to suggest you check out Boxcars for better performance, but you already have! https://github.com/nickbabcock/boxcars/issues/25

**Comment by jjbott** [comment]
Hi! In theory the version in master is .NET Core-ified, so it should be possible to run it in Linux. I haven't tried though. I haven't updated the console app release in quite a while since I don't think anyone uses it (using the library directly through Nuget is more common) but I should be able to do that later tonight.

Also, I haven't done a done of performance tuning. For the most part I'm just happy it works. :)

**Comment by nickbabcock** [comment]
> Also, I haven't done a done of performance tuning

In case you are curious, the last I looked, major performance can be gained by avoiding all strings in the network code (eg: no string hashing or comparisons (a la a dictionary lookup or switch statements)) -- only deal with integers, and a faster bit stream implementation (I haven't looked at haskell or C# to see if they are sufficient).

But yeah, no need to fret over performance as it can be a never ending struggle 😄

**Comment by jjbott** [comment]
Yeah, I definitely use string dictionaries so that could be improved. If I remember right the conversion to JSON was actually the slowest by far, and that's mostly handled by a third party library - beyond some cleanup to make it less redundant.

I forgot to release the console app last night. I'll do it tonight! Probably!

**Comment by dtracers** [comment]
Yeah we were looking into moving to boxcar and taking ownership of it.  Our goal is to not create json for the majority of the repeated data in the network part and instead create a matrix.

So we were more wondering if you had any interest in moving to rust with us.  It seems that json Creation is the fastest of the 3 in boxcar. (this one, rattletrap, boxcar)
